/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'profile.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'profile.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('model\index.js'),
    model   = require('./profile.js'),
    util    = require('../utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("user").onDelete = 'CASCADE'; 
util.getAttribute("id").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.profile",
    options: {
        tableName: "profile",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "id": {
            type: Seq.BIGINT,
            field: "id",
            primaryKey: true,
            allowNull: false,
            unique: "profile_pk"
        },
        "userId": {
            type: Seq.INTEGER,
            field: "user_id",
            references: "public.users",
            referencesKey: "user_id"
        },
        "profilName": {
            type: Seq.ARRAY(Seq.CHAR(50)),
            field: "profil_name"
        }
    },
    relations: [{
        type: "belongsTo",
        model: "public.users",
        schema: "public",
        table: "users",
        source: "generator",
        details: {
            as: "user",
            foreignKey: "user_id",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};