/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'automatic.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'automatic.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('model\index.js'),
    model   = require('./automatic.js'),
    util    = require('../utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:

util.getAttribute("col1").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.automatic",
    options: {
        tableName: "automatic",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "col1": {
            type: Seq.CHAR(1),
            field: "col1",
            primaryKey: true,
            allowNull: false,
            unique: "auto_PK"
        },
        "col2": {
            type: Seq.CHAR(1),
            field: "col2"
        },
        "col3": {
            type: Seq.CHAR(1),
            field: "col3"
        }
    },
    relations: []
};