/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'RetailerRoute.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'RetailerRoute.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('model\index.js'),
    model   = require('./RetailerRoute.js'),
    util    = require('../utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("relatedRetailerID").onDelete = 'CASCADE'; 
util.getAttribute("routeID").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.retailerRoute",
    options: {
        tableName: "RetailerRoute",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "routeID": {
            type: Seq.INTEGER,
            field: "routeID",
            primaryKey: true,
            autoIncrement: true,
            allowNull: false,
            unique: "RetailerRouter_PK"
        },
        "userID": {
            type: Seq.INTEGER,
            field: "userID"
        },
        "retailerID": {
            type: Seq.INTEGER,
            field: "retailerID",
            references: "public.retailer",
            referencesKey: "retailerID"
        },
        "routeDate": {
            type: Seq.DATEONLY,
            field: "routeDate"
        },
        "routeNumber": {
            type: Seq.INTEGER,
            field: "routeNumber"
        }
    },
    relations: [{
        type: "belongsTo",
        model: "public.retailer",
        schema: "public",
        table: "Retailer",
        source: "generator",
        details: {
            as: "relatedRetailerID",
            foreignKey: "retailerID",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};